"""Generate portable standalone Codex roles from one model map and shared prompts."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

ROOT = Path(__file__).resolve().parents[1]
EFFORTS = {"none", "low", "medium", "high", "xhigh", "max"}
MODELS = {"gpt-5.6-luna", "gpt-5.6-terra", "gpt-5.6-sol", "gpt-6-astra"}


def load_catalog(root=ROOT):
    data = json.loads((root / "agents/catalog.json").read_text(encoding="utf-8"))
    if data.get("schemaVersion") != 1:
        raise ValueError("Unsupported agent catalog schema")
    roles = data["roles"]
    names = [r["name"] for r in roles]
    if len(names) != len(set(names)):
        raise ValueError("Duplicate role names")
    for role in roles:
        if not re.fullmatch(r"[a-z][a-z0-9_]*", role["name"]):
            raise ValueError("Invalid role name")
        if role["model"] not in MODELS or role["effort"] not in EFFORTS:
            raise ValueError(f"Unsupported model/effort for {role['name']}")
        if role["sandbox"] not in {"read-only", "workspace-write"}:
            raise ValueError("Unsupported sandbox")
        if not re.fullmatch(r"[a-z]+", role["template"]):
            raise ValueError("Invalid template name")
        if not (root / "agents/prompts" / (role["template"] + ".md")).is_file():
            raise ValueError(f"Missing prompt for {role['name']}")
        if any(f not in names or f == role["name"] for f in role["fallbacks"]):
            raise ValueError(f"Invalid fallback for {role['name']}")
    graph = {r["name"]: r["fallbacks"] for r in roles}
    def visit(name, ancestors):
        if name in ancestors:
            raise ValueError("Fallback cycle")
        for child in graph[name]:
            visit(child, ancestors | {name})
    for name in names:
        visit(name, set())
    for key in ("main", "defaultSubagent"):
        if data[key]["model"] not in MODELS or data[key]["effort"] not in EFFORTS:
            raise ValueError(f"Invalid {key} configuration")
    if not isinstance(data["maxConcurrent"], int) or not 1 <= data["maxConcurrent"] <= 32:
        raise ValueError("Invalid concurrency limit")
    if type(data.get("maxDepth")) is not int or not 1 <= data["maxDepth"] <= 2:
        raise ValueError("Invalid delegation depth; this kit supports main, coordinator, and leaf")
    return data


def render(root=ROOT):
    data = load_catalog(root)
    common = (root / "agents/prompts/common.md").read_text(encoding="utf-8").strip()
    outputs = {}
    for role in data["roles"]:
        body = (root / "agents/prompts" / (role["template"] + ".md")).read_text(encoding="utf-8").strip()
        delegation = ("Spawn only web_searcher, docs_researcher or web_verifier for this bounded research assignment."
                      if role["template"] == "coordinate" else "Do not spawn agents. Return follow-up assignments to the main agent.")
        fallback = ("If this model is unavailable, the parent may use " + ", ".join(role["fallbacks"]) + " if it preserves the assignment and required capability."
                    if role["fallbacks"] else "No automatic model fallback is configured; report unavailability to the parent.")
        fields = {"name": role["name"], "description": role["description"], "model": role["model"],
                  "model_reasoning_effort": role["effort"], "sandbox_mode": role["sandbox"],
                  "developer_instructions": "\n\n".join((common, body, delegation, fallback))}
        text = "# Generated by scripts/agents.py; edit agents/catalog.json or agents/prompts instead.\n"
        text += "\n".join(f"{k} = {json.dumps(v, ensure_ascii=False)}" for k, v in fields.items()) + "\n"
        tomllib.loads(text)
        outputs[f".codex/agents/{role['name']}.toml"] = text
    outputs[".codex/config.toml"] = (
        "# Generated by scripts/agents.py from agents/catalog.json.\n"
        "# Project defaults; explicit app/session choices may override these values.\n"
        f'model = "{data["main"]["model"]}"\nmodel_reasoning_effort = "{data["main"]["effort"]}"\n\n'
        "[agents]\nenabled = true\n"
        f'max_concurrent_threads_per_session = {data["maxConcurrent"]}\n'
        f'max_depth = {data["maxDepth"]}\n'
        f'default_subagent_model = "{data["defaultSubagent"]["model"]}"\n'
        f'default_subagent_reasoning_effort = "{data["defaultSubagent"]["effort"]}"\n'
    )
    return outputs


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write generated project config and role files")
    parser.add_argument("--check", action="store_true", help="Check without writing (default)")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args(argv)
    if args.write and args.check:
        parser.error("Choose --write or --check")
    try:
        outputs = render(args.root)
        issues = []
        for relative, text in outputs.items():
            path = args.root / relative
            if args.write:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
            elif not path.exists() or path.read_text(encoding="utf-8") != text:
                issues.append("Missing or stale: " + relative)
        for path in (args.root / ".codex/agents").glob("*.toml"):
            if path.relative_to(args.root).as_posix() not in outputs:
                issues.append("Obsolete/unmanaged role (preserved): " + str(path))
        for issue in issues:
            print(issue)
        print(f"{'Generated' if args.write else 'Checked'} {len(outputs)-1} roles and project defaults")
        return 1 if issues else 0
    except (ValueError, KeyError, OSError) as exc:
        print(f"Agent catalog error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
